version: '3.9'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: vCdGUL22
      MYSQL_DATABASE: omniverse
      MYSQL_USER: Itaymer
      MYSQL_PASSWORD: vCdGUL22
      MYSQL_ROOT_HOST: '%'
      DB_HOST: '%'
    ports:
      - "3306:3306"


